import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

export const ORCH_MANAGED_MARKER = "<!-- orch-managed:v1 -->";

export type ManagedWriteResult =
  | "created"
  | "updated"
  | "unchanged"
  | "adopted-legacy"
  | "skipped-user-file";

export interface ManagedWriteOptions {
  isLegacyOrchFile?: (current: string) => boolean;
}

export function withManagedMarker(content: string): string {
  const normalized = content.replace(/^\uFEFF/, "");
  if (normalized.startsWith(ORCH_MANAGED_MARKER)) return normalized;
  return `${ORCH_MANAGED_MARKER}\n${normalized}`;
}

export async function writeManagedFile(
  destination: string,
  content: string,
  options: ManagedWriteOptions = {}
): Promise<ManagedWriteResult> {
  await mkdir(path.dirname(destination), { recursive: true });
  const normalizedSource = content.replace(/^\uFEFF/, "");
  const next = withManagedMarker(normalizedSource);

  try {
    const current = await readFile(destination, "utf8");

    if (!current.startsWith(ORCH_MANAGED_MARKER)) {
      // Migration path for files generated by Orch before managed markers existed.
      // Exact source matches are always safe to adopt. Older known Orch templates
      // may also be adopted through the caller's conservative legacy detector.
      if (current === normalizedSource || options.isLegacyOrchFile?.(current)) {
        await writeFile(destination, next, "utf8");
        return "adopted-legacy";
      }
      return "skipped-user-file";
    }

    if (current === next) return "unchanged";
    await writeFile(destination, next, "utf8");
    return "updated";
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code !== "ENOENT") throw error;
    await writeFile(destination, next, "utf8");
    return "created";
  }
}
