import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

export const ORCH_MANAGED_MARKER = "<!-- orch-managed:v1 -->";

export type ManagedWriteResult = "created" | "updated" | "unchanged" | "skipped-user-file";

export function withManagedMarker(content: string): string {
  const normalized = content.replace(/^\uFEFF/, "");
  if (normalized.startsWith(ORCH_MANAGED_MARKER)) return normalized;
  return `${ORCH_MANAGED_MARKER}\n${normalized}`;
}

export async function writeManagedFile(
  destination: string,
  content: string
): Promise<ManagedWriteResult> {
  await mkdir(path.dirname(destination), { recursive: true });
  const normalizedSource = content.replace(/^\uFEFF/, "");
  const next = withManagedMarker(normalizedSource);

  try {
    const current = await readFile(destination, "utf8");

    if (!current.startsWith(ORCH_MANAGED_MARKER)) {
      // Migration path for files generated by Orch before managed markers existed.
      // Only adopt the file when its content exactly matches the shipped source;
      // otherwise treat it as user-authored and preserve it.
      if (current === normalizedSource) {
        await writeFile(destination, next, "utf8");
        return "updated";
      }
      return "skipped-user-file";
    }

    if (current === next) return "unchanged";
    await writeFile(destination, next, "utf8");
    return "updated";
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code !== "ENOENT") throw error;
    await writeFile(destination, next, "utf8");
    return "created";
  }
}
